/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author alexi
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnSuma = new javax.swing.JButton();
        BtnPotencia = new javax.swing.JButton();
        BtnRaiz = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        Btn10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TxtResultados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(43, 60, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSuma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BtnSuma.setText("+");
        BtnSuma.setName(""); // NOI18N
        jPanel1.add(BtnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 23, 70, 71));

        BtnPotencia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BtnPotencia.setText("^");
        BtnPotencia.setName(""); // NOI18N
        jPanel1.add(BtnPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 23, 75, 71));

        BtnRaiz.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BtnRaiz.setText("√");
        BtnRaiz.setName(""); // NOI18N
        jPanel1.add(BtnRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 23, 71, 71));

        Btn3.setBackground(new java.awt.Color(50, 102, 81));
        Btn3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Btn3.setText("3");
        Btn3.setName(""); // NOI18N
        jPanel1.add(Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 70, 70));

        Btn1.setBackground(new java.awt.Color(50, 102, 81));
        Btn1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Btn1.setText("1");
        Btn1.setName(""); // NOI18N
        jPanel1.add(Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 71));

        Btn2.setBackground(new java.awt.Color(50, 102, 81));
        Btn2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Btn2.setText("2");
        Btn2.setName(""); // NOI18N
        jPanel1.add(Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 70, 71));

        Btn4.setBackground(new java.awt.Color(50, 102, 81));
        Btn4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Btn4.setText("4");
        Btn4.setName(""); // NOI18N
        jPanel1.add(Btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, 71));

        Btn5.setBackground(new java.awt.Color(50, 102, 81));
        Btn5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Btn5.setText("5");
        Btn5.setName(""); // NOI18N
        jPanel1.add(Btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 70, 71));

        Btn6.setBackground(new java.awt.Color(50, 102, 81));
        Btn6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Btn6.setText("6");
        Btn6.setName(""); // NOI18N
        jPanel1.add(Btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 70, 71));

        Btn7.setBackground(new java.awt.Color(50, 102, 81));
        Btn7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Btn7.setText("7");
        Btn7.setName(""); // NOI18N
        jPanel1.add(Btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 70, 71));

        Btn8.setBackground(new java.awt.Color(50, 102, 81));
        Btn8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Btn8.setText("8");
        Btn8.setName(""); // NOI18N
        jPanel1.add(Btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 70, 71));

        Btn9.setBackground(new java.awt.Color(50, 102, 81));
        Btn9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Btn9.setText("9");
        Btn9.setToolTipText("");
        Btn9.setName(""); // NOI18N
        jPanel1.add(Btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 70, 71));

        Btn10.setBackground(new java.awt.Color(50, 102, 81));
        Btn10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Btn10.setText("9");
        Btn10.setName(""); // NOI18N
        jPanel1.add(Btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 70, 71));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 620, 400));

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));

        TxtResultados.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 48)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 615, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn10;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnPotencia;
    private javax.swing.JButton BtnRaiz;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JTextField TxtResultados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
